### Homework 2. NumPy

In [1]:
import numpy as np
data = np.loadtxt('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', dtype='object', delimiter=',')
data.shape

(150, 5)

__1. Знайти в датасеті таргет та видалити цю колонку з датасету (видаляти за індексом)__

In [2]:
data[:10]

array([['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'],
       ['4.9', '3.0', '1.4', '0.2', 'Iris-setosa'],
       ['4.7', '3.2', '1.3', '0.2', 'Iris-setosa'],
       ['4.6', '3.1', '1.5', '0.2', 'Iris-setosa'],
       ['5.0', '3.6', '1.4', '0.2', 'Iris-setosa'],
       ['5.4', '3.9', '1.7', '0.4', 'Iris-setosa'],
       ['4.6', '3.4', '1.4', '0.3', 'Iris-setosa'],
       ['5.0', '3.4', '1.5', '0.2', 'Iris-setosa'],
       ['4.4', '2.9', '1.4', '0.2', 'Iris-setosa'],
       ['4.9', '3.1', '1.5', '0.1', 'Iris-setosa']], dtype=object)

In [3]:
data = np.delete(data, -1, axis=1)

In [4]:
data[:10]

array([['5.1', '3.5', '1.4', '0.2'],
       ['4.9', '3.0', '1.4', '0.2'],
       ['4.7', '3.2', '1.3', '0.2'],
       ['4.6', '3.1', '1.5', '0.2'],
       ['5.0', '3.6', '1.4', '0.2'],
       ['5.4', '3.9', '1.7', '0.4'],
       ['4.6', '3.4', '1.4', '0.3'],
       ['5.0', '3.4', '1.5', '0.2'],
       ['4.4', '2.9', '1.4', '0.2'],
       ['4.9', '3.1', '1.5', '0.1']], dtype=object)

__2. Перетворити колонки, що залишились в 2D масив (або впевнитись, що це уже 2D масив)__

In [5]:
data.ndim

2

__3. Порахувати mean, median, standard deviation для 1-ї колонки__


In [6]:
data = data.astype('float')

In [7]:
print("Mean value is: ", np.mean(data[:,0]))
print("Median value is: ", np.median(data[:,0]))
print("Standard deviation value is: ", np.std(data[:,0]))

Mean value is:  5.843333333333334
Median value is:  5.8
Standard deviation value is:  0.8253012917851409


__4. Вставити 20 значень np.nan на випадкові позиції в масиві 
(при використанні звичайного рандому можуть накластись позиції, тому знайти рішення, яке гарантує 20 унікальних позицій)__

In [8]:
rng = np.random.default_rng()
ravel_data = data.ravel()
idx = rng.choice(data.size, size=20, replace=False)
ravel_data[idx] = np.nan

In [9]:
np.isnan(data).sum()

20

__5. Знайти позиції вставлених значень np.nan в 1-й колонці__

In [10]:
np.where(np.isnan(data[:, 0]))

(array([ 14,  34,  35,  40,  64,  84, 101, 113, 114, 123, 124, 128, 137],
       dtype=int64),)

__6. Відфільтрувати массив за умовою: значення в 3-й колонці > 1.5 та значения в 1-й колонці < 5.0__

In [11]:
mask = (data[:, 2] > 1.5) & (data[:, 0] < 5.0)
print(data[mask])

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


__7. Замінити всі значення np.nan на 0__

In [12]:
data[np.isnan(data)] = 0

In [13]:
np.isnan(data).sum()

0

In [14]:
#кількість нулів в масиві (перевірка)
num_zeros = data.size - np.count_nonzero(data)
print(num_zeros)

20


__8. Порахувати всі унікальні значення в массиві та вивести їх разом із кількістю__

In [15]:
uniqs, counts = np.unique(data, return_counts=True)
print("Unique items: ", uniqs)
print("Counts: ", counts)

Unique items:  [0.  0.1 0.2 0.3 0.4 0.5 0.6 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.
 2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8
 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3 5.4 5.5 5.6
 5.7 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1 7.2 7.3 7.4
 7.6 7.7 7.9]
Counts:  [20  6 27  7  7  1  1  8  4  6 19 19 25 11  6 12  7  7  6  6 12  6 11  5
  8 14 10 27 11 13  8 12  8  4  4  7  5  6  4  5  3  8  9  7  7  9 10 12
 17  6  3  7 10 11 10  7  5  8  9  4  9  6  5  3  9  3  5  1  1  3  1  1
  1  4  1]


__9. Розбити масив по горизонталі на 2 рівні частини (не використовувати абсолютні числа, мають бути два массиви по 4 колонки)__

In [16]:
data_1, data_2 = np.split(data, 2, axis=0)

__10. Відсортувати обидва массиви по 1-й колонці: 1-й за збільшенням, 2-й за зменшенням__

In [17]:
sorted_data_1 = data_1[data_1[:, 0].argsort()]
sorted_data_2 = data_2[data_2[:, 0].argsort()[::-1]]

__11. Зібрати обидва массиви в одне ціле__

In [18]:
data = np.concatenate([data_1, data_2], axis=0)

__12. Знайти найбільш часто повторюване значення в массиві__

In [19]:
uniqs, counts = np.unique(data, return_counts=True)
uniqs[np.argmax(counts)]

0.2

__13. Написати функцію, яка б множила всі значення в колонці, які менше середнього значения в цій колонці, на 2, і ділила інші значення на 4.__

In [20]:
def compar_mean(d): 
    return np.select([d < d.mean(), d >= d.mean()], [d * 2, d / 4])

__14. Застосувати отриману функцію до 3-ї колонки__

In [21]:
compar_mean(data[:, 2])

array([2.8  , 2.8  , 2.6  , 3.   , 0.   , 3.4  , 2.8  , 3.   , 2.8  ,
       3.   , 3.   , 3.2  , 2.8  , 2.2  , 2.4  , 3.   , 2.6  , 2.8  ,
       3.4  , 3.   , 3.4  , 3.   , 2.   , 3.4  , 3.8  , 3.2  , 3.2  ,
       3.   , 2.8  , 3.2  , 3.2  , 0.   , 3.   , 2.8  , 3.   , 2.4  ,
       2.6  , 3.   , 2.6  , 3.   , 2.6  , 2.6  , 2.6  , 3.2  , 3.8  ,
       2.8  , 3.2  , 2.8  , 3.   , 2.8  , 1.175, 1.125, 1.225, 1.   ,
       1.15 , 1.125, 1.175, 6.6  , 1.15 , 0.975, 7.   , 1.05 , 1.   ,
       1.175, 7.2  , 1.1  , 1.125, 1.025, 1.125, 0.975, 1.2  , 1.   ,
       1.225, 1.175, 1.075, 1.1  , 1.2  , 1.25 , 1.125, 7.   , 0.95 ,
       7.4  , 0.975, 1.275, 1.125, 1.125, 1.175, 1.1  , 1.025, 1.   ,
       1.1  , 1.15 , 1.   , 6.6  , 1.05 , 1.05 , 1.05 , 1.075, 6.   ,
       1.025, 1.5  , 1.275, 1.475, 1.4  , 1.45 , 1.65 , 1.125, 1.575,
       1.45 , 1.525, 1.275, 1.325, 1.375, 1.25 , 1.275, 1.325, 1.375,
       1.675, 1.725, 1.25 , 1.425, 1.225, 1.675, 1.225, 1.425, 1.5  ,
       1.2  , 1.225,